### ISSUE TITLE
[DoE] Anti-Grav Belt skin size too large

### ISSUE THREAD

**Issue by Riccardoman** [NightFright2k19/quake_authmdl#3] opened 2021-02-27 00:57 UTC
Getting this error while loading r2m8 in Vkquake
![Screenshot (1336)](https://user-images.githubusercontent.com/74624503/109369985-e067d880-789e-11eb-9809-01843f407a99.jpg)

**Comment by NightFright2k19** [comment] 2021-02-27 07:21
If vkQuake cannot handle skins with specific sizes, it's an issue with that port, not with our mod and its contents. Works fine in other common ports.

Open an issue over at vkQuake about this since it needs to be addressed through the port.

**Comment by Novum** [comment] 2021-02-28 20:10
This is not a vkQuake limit, 480 is the maximum height in QuakeSpasm too, and as a matter of fact also in the original Quake.

**Comment by mmillar-bolis** [comment] 2021-02-28 21:41
I am also able to reproduce this error in Quakespasm 0.93.2 for Windows, both 32-bit and 64 bit. The ModDB page doesn't specify what engines are supported or tested, but perhaps the authors only support Spiked and Darkplaces now?

EDIT: I just tried this in the latest release of Quakespasm Spiked for Win64 and did not receive any error on r2m8. It looks like the issue only affects vanilla Quake engines.

**Comment by NightFright2k19** [comment] 2021-02-28 22:09
We'll look into this issue to increase port compatibility with the next release.

**Comment by NightFright2k19** [comment] 2021-03-01 10:29
Should be fixed in Rev. #24.

**Closed as completed by NightFright2k19** 2021-03-01 10:29 UTC
